assignment_name="A8_DocumentSimiliarty"
semester="S25"

[config]
    impl_to_use="Python"
    autograder_version="5.1.0"

    test_directory="./student_tests"

    enforce_submission_limit=true
    submission_limit=5

    take_highest=true

    allow_extra_credit=false
    perfect_score=28
    max_score=28


[config.python]


[build]
    use_starter_code=false
    use_data_files=false
    allow_private=true

    build_student=true

    build_gradescope=true

    student_work_folder="student_work"
    private_tests_regex='^test_private_?\w*\.py$'
    public_tests_regex='^test_public_?\w*\.py$'

