assignment_name="A12_ImageCompression"
semester="S25"

[config]
    impl_to_use="Python"
    autograder_version="5.1.0"

    test_directory="./student_tests"

    enforce_submission_limit=true
    submission_limit=3

    take_highest=true

    allow_extra_credit=false
    perfect_score=14
    max_score=14


[config.python]
    buffer_size=20971520 # 10 * 2 ** 21


[build]

    # Things that need to be considered when building
    use_starter_code=true
    starter_code_source="./starter_code/helper_library.py"
    use_data_files=true
    data_files_source="student_tests/data/"
    
    allow_private=true

    build_student=true

    build_gradescope=true

    student_work_folder="student_work"
    private_tests_regex='^test_private_?\w*\.py$'
    public_tests_regex='^test_public_?\w*\.py$'

